/** @type {import('stylelint').Config} */
export default {
	extends: ['stylelint-config-standard'],
	ignoreFiles: [
		'**/node_modules/**',
		'../src/www/admin/static/dist/**',
		'src/admin/legacy/**',
		'src/admin/media/print.css',
		'src/brindille/content-paheko.css',
	],
	rules: {
		'at-rule-no-unknown': [
			true,
			{
				ignoreAtRules: ['theme', 'source', 'layer', 'bottom'],
			},
		],
		'at-rule-empty-line-before': null,
		'at-rule-descriptor-no-unknown': null,
		'selector-class-pattern': null,
		'selector-id-pattern': null,
		'selector-attribute-quotes': null,
		'selector-pseudo-element-colon-notation': null,
		'selector-not-notation': null,
		'font-family-name-quotes': null,
		'font-family-no-missing-generic-family-keyword': null,
		'length-zero-no-unit': null,
		'color-hex-length': null,
		'custom-property-empty-line-before': null,
		'custom-property-pattern': null,
		'declaration-block-no-duplicate-properties': null,
		'no-duplicate-selectors': null,
		'shorthand-property-no-redundant-values': null,
		'declaration-block-no-redundant-longhand-properties': null,
		'declaration-block-single-line-max-declarations': null,
		'declaration-property-value-keyword-no-deprecated': null,
		'hue-degree-notation': null,
		'comment-empty-line-before': null,
		'rule-empty-line-before': null,
		'alpha-value-notation': null,
		'color-function-alias-notation': null,
		'color-function-notation': null,
		'media-feature-range-notation': null,
		'import-notation': null,
		'no-descending-specificity': null,
		'property-no-vendor-prefix': null,
		'value-no-vendor-prefix': null,
		'value-keyword-case': null,
		'property-no-unknown': [
			true,
			{
				ignoreProperties: ['prince-link'],
			},
		],
	},
};
